name: placebase-dev
services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    tty: true
    volumes:
      - .:/project
      - cache:/home/node/.cache
    network_mode: "host"
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: ["npm", "run", "test"]
    network_mode: "host"
volumes:
  cache:
