FROM node:22

# Add the Microsoft OpenJDK repository
RUN apt update && \
	apt install wget lsb-release -y && \
	wget "https://packages.microsoft.com/config/debian/$(lsb_release -rs)/packages-microsoft-prod.deb" -O packages-microsoft-prod.deb && \
	dpkg -i packages-microsoft-prod.deb
# Install OpenJDK
RUN apt update && apt install msopenjdk-21 -y

# Docker Compose will mount a name volume as root if the directory doesn't exist
RUN mkdir /home/node/.cache
RUN chown node:node /home/node/.cache

WORKDIR /project

USER node

RUN npm config set update-notifier false

CMD ["bash"]
