FROM node:22

# Add the Microsoft OpenJDK repository
RUN apt update && \
	apt install wget lsb-release -y && \
	wget "https://packages.microsoft.com/config/debian/$(lsb_release -rs)/packages-microsoft-prod.deb" -O packages-microsoft-prod.deb && \
	dpkg -i packages-microsoft-prod.deb
# Install OpenJDK
RUN apt update && apt install msopenjdk-21 -y

WORKDIR /placebase

COPY . .

RUN npm config set update-notifier false

RUN npm ci
