ALTER TABLE IF EXISTS ONLY public.subregions DROP CONSTRAINT IF EXISTS subregions_region_id_fkey;
ALTER TABLE IF EXISTS ONLY public.states DROP CONSTRAINT IF EXISTS states_country_id_fkey;
ALTER TABLE IF EXISTS ONLY public.countries DROP CONSTRAINT IF EXISTS countries_subregion_id_fkey;
ALTER TABLE IF EXISTS ONLY public.countries DROP CONSTRAINT IF EXISTS countries_region_id_fkey;
ALTER TABLE IF EXISTS ONLY public.cities DROP CONSTRAINT IF EXISTS cities_state_id_fkey;
ALTER TABLE IF EXISTS ONLY public.cities DROP CONSTRAINT IF EXISTS cities_country_id_fkey;
DROP INDEX IF EXISTS public.subregions_region_id_idx;
DROP INDEX IF EXISTS public.states_country_id_idx;
DROP INDEX IF EXISTS public.countries_subregion_id_idx;
DROP INDEX IF EXISTS public.countries_region_id_idx;
DROP INDEX IF EXISTS public.cities_state_id_idx;
DROP INDEX IF EXISTS public.cities_country_id_idx;
ALTER TABLE IF EXISTS ONLY public.subregions DROP CONSTRAINT IF EXISTS subregions_pkey;
ALTER TABLE IF EXISTS ONLY public.states DROP CONSTRAINT IF EXISTS states_pkey;
ALTER TABLE IF EXISTS ONLY public.regions DROP CONSTRAINT IF EXISTS regions_pkey;
ALTER TABLE IF EXISTS ONLY public.countries DROP CONSTRAINT IF EXISTS countries_pkey;
ALTER TABLE IF EXISTS ONLY public.cities DROP CONSTRAINT IF EXISTS cities_pkey;
DROP TABLE IF EXISTS public.subregions;
DROP TABLE IF EXISTS public.states;
DROP TABLE IF EXISTS public.regions;
DROP TABLE IF EXISTS public.countries;
DROP TABLE IF EXISTS public.cities;
