name: Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build container for tests
        run: docker compose -f compose.ci.yaml build
      - name: Run tests
        run: docker compose -f compose.ci.yaml run --rm test
